from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.String(), nullable=True))
    op.add_column('user', sa.Column('role_id', sa.Integer(), nullable=True))

    op.create_table('user_role_link',
                sa.Column('user_id', sa.Integer(), nullable=False),
                sa.Column('role_id', sa.Integer(), nullable=False),
                sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
                sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_role_id', 'user', type_='foreignkey')
    op.drop_column('user', 'role_id')
    op.drop_column('user', 'role')
    # ### end Alembic commands ###